### ISSUE TITLE
https not http

### ISSUE THREAD

**Issue by quentinwin** [branchnetconsulting/so1404-ntopng-installer#8]
Not sure if this is an issue, but may be helpful to others coming across the same problem. At the moment you have to edit the install_ntopng_on_so_16 file before running it, to change every url from http to https, or it fails saying "The official ntop repository is unreachable or broken"

**Comment by branchnetconsulting** [comment]
Thanks, indeed ntop.org apparently started requiring https and I had not caught that yet.   It should be good now.
